name: Push Notifier

on:
  push:
    branches:
      - main  # main ブランチに push されたときに実行

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Print push notification
        run: echo "✅ ${{ env.timestamp }} に push されました！"
